### ISSUE TITLE
Translation table specification

### ISSUE THREAD

**Issue by jwestrob** [althonos/pyrodigal#1]
Hi! You've made a really awesome tool here and I'm excited to use it. I'm making a script that looks at coding densities using various different translation tables, and it would be incredibly useful to be able to use pyrodigal for this. I don't see any way yet to specify the translation table when translating (prodigal's `-g` flag); is there a way to do this? 

Thanks so much!

Jacob

**Comment by althonos** [comment]
Hi @jwestrob , thanks for using this!

Translation tables are handled differently in metagenomic mode and in training mode:

- in metagenomic mode, the translation tables are hardcoded with several metagenomic profiles, and the best one is used for detection and translation.
- in training mode, you can specify the training table with the `trans_table` argument

In both cases, you can get the translation table that was used for gene finding with the `translation_table` property on the `Gene` instances you get. So if you wanted to do things as intended by Prodigal, you'd have to retrain with a different translation table before running the gene finding for each of them.

I guess what you're asking here is a way to do the gene finding only once, and then be able to specify different translation tables directly to the `Gene.translate` method? I'm not entirely sure this is possible, but I can have a look at Prodigal's code.

**Comment by althonos** [comment]
> I guess what you're asking here is a way to do the gene finding only once, and then be able to specify different translation tables directly to the Gene.translate method? I'm not entirely sure this is possible, but I can have a look at Prodigal's code.

Actually this is feasible with the current Prodigal internals. If this is what you need, I can implement it.

**Comment by jwestrob** [comment]
This is precisely what I need to do! I'm only interested in translation
tables 4, 11, and 15; 4 and 15 differ from 11 (bacterial standard) only
because of their re-coded stop codon. So I think everything about the gene
finding should be fine the way it is.

I'm working with whole metagenome assemblies, and Pyrodigal is perfect
because it lets me parallelize without splitting up the original fasta file
(and slamming our cluster's disk I/O). Turns out running prodigal with
three different translation tables on a whole metagenome takes a really
long time, even when you run the three in parallel.

I'm really glad this is feasible to implement and I'm very thankful for
your quick response. I look forward to using it and can't wait to have a
paper where I can cite you!

Thanks a bunch.

Jacob

--

*Jacob West-Roberts, MS*
*Ph.D. Candidate, Banfield Lab*

**Comment by althonos** [comment]
Hi @jwestrob , this is now be feasible in `v0.4.0` that I just released. Tell me if works for you! You should be able to do something like:
```python
import pyrodigal

finder = pyrodigal.Pyrodigal(meta=True)
for gene in finder.find_genes("ATGC..."):
    protein_bact = gene.translate(translation_table=11)
    protein_yeast = gene.translate(translation_table=12)
```

> I'm really glad this is feasible to implement and I'm very thankful for
your quick response. I look forward to using it and can't wait to have a
paper where I can cite you!

I guess so paper write-up is in order then :wink: In the meantime, there is a versioned Zenodo DOI available, either for all versions, or for the exact version you use in your analysis! 

Thanks for the feedback!
