### ISSUE TITLE
Is it possible to exclude amino acids predicted as unknown - 'X'

### ISSUE THREAD

**Issue by linda5mith** [althonos/pyrodigal#10]
I'm using PhageBoost which depends on pyrodigal to predict the protein sequence but it breaks if there is an unknown AA - 'X'. Is it possible to force prodigal to predict an AA or just exclude the unknown amino acids?

**Comment by linda5mith** [comment]
Lovely, thanks for your swift reply!

**Comment by althonos** [comment]
There was a bug in previous versions that caused the `translate` method to always ignore the replacement character, but it was fixed in `v0.7.1`. Hopefully this solves your question!
