### ISSUE TITLE
Excessive memory use

### ISSUE THREAD

**Issue by KGerhardt** [althonos/pyrodigal#12]
I've incorporated pyrodigal into a script I'm working on and I noticed when I ran it on a larger batch of genomes that the memory usage kept increasing over time. I went back and tested a few different approaches with the same issue. Even using the same OrfFinder object and retraining it continues to increase RAM use.

Is it possible to add a python-level deallocation function to the OrfFinder class?

**Comment by althonos** [comment]
Hi @KGerhardt , thank you for the feedback.

A few questions here:
- Are you using single or metagenomic mode?
- Which version are you using? There was a memory leak I fixed in `v0.7.1` that affected the training step.

**Comment by KGerhardt** [comment]
I was using single mode and I had version 0.6.4 installed.

I upgraded to 0.7.2 and I'm rerunning the test that caused the memory usage issue. It's looking like that fixed it for me. 

Thank you for responding so quickly. I apologize for flagging an issue that you'd already fixed.

**Comment by althonos** [comment]
No problem, that's why I waw checking! I'd rather have it be that than a new memory leak I'm unaware of. 😁

**Comment by althonos** [comment]
Thanks a lot @KGerhardt , I'm really happy to hear the work I have done turns out to be useful to other people. I'm actually experimenting with a way to accelerate FastANI at the moment, I'm not sure if I'll manage to go somewhere, but let's see :)
