### ISSUE TITLE
Bioconda update to v1.1.0 is blocked

### ISSUE THREAD

**Issue by jhahnfeld** [althonos/pyrodigal#17]
Hello Martin,

thank you very much for developing Pyrodigal.
I would like to use the latest version (v1.1.0) of Pyrodigal from Bioconda, but something is blocking the [update](https://github.com/bioconda/bioconda-recipes/pull/35302) from version 1.0.2 to 1.1.0 and I could not find the error. 

Could you have a look at what is blocking the update?

Thanks,

Julian

**Comment by althonos** [comment]
Fixed in bioconda/bioconda-recipes#35735.

Actually was great that you opened this PR, I forgot to include some C source files in the sdist, meaning not only conda but any install not using the wheels would fail 😅
