### ISSUE TITLE
GFF seqid may violate gff3 spec

### ISSUE THREAD

**Issue by zdk123** [althonos/pyrodigal#18]
Thanks for this tool! One comment and a request:

It looks like the GFF output format here is slightly different than prodigal, and (maybe) the [gff3 specs](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md). This is preventing us using pyrodigal as a drop-in replacement.

Prodigal uses the [input contig name](https://github.com/hyattpd/Prodigal/blob/6ccc8d1ca126969be402e5bf495ed31a74f7edd5/sequence.c#L155) for the `seqid`, while pyrodigal uses [`prefix/gene_{i}`](https://github.com/althonos/pyrodigal/blob/9a1052177fe73dbdf604aa41fb1ba120ddfaa440/pyrodigal/_pyrodigal.pyx#L3214-L3215) , which seems to violate this spec:
> Column 1: "seqid"
> The ID of the landmark used to establish the coordinate system for the current feature...

The landmark for the gene coordinates obviously cannot be the gene id itself.

What would be great is if instead the prefix could modify the `ID` component of the [`_gene_data`](https://github.com/althonos/pyrodigal/blob/9a1052177fe73dbdf604aa41fb1ba120ddfaa440/pyrodigal/_pyrodigal.pyx#L2508) which would add an enhancement over the gff output provided by prodigal without violating the spec.

**Comment by althonos** [comment]
Oh yes, this is a mistake on my end, sorry :zipper_mouth_face: I'll update this part for `v1.2`.

**Comment by althonos** [comment]
I'm pushing a pre-release that you can test on your side (`v2.0.0-rc.1`). This will need a bump in major version since I ended up changing the signature of all write methods. I'll try to fix #19 before releasing the actual v2.

**Comment by zdk123** [comment]
Wow that was fast, thank you I'll test this out soon!

**Comment by althonos** [comment]
Marking this as fixed since `v2.0.0` will now use the sequence identifier in the first column and create a gene identifier for the `ID` attribute.
