### ISSUE TITLE
tests failing in archlinux

### ISSUE THREAD

**Issue by kbipinkumar** [althonos/pyrodigal#33]
i am attemping build archlinux package using `PKGBUILD`  from aur. the process errors out at the `check()` stage with following output

```
==> Starting check()...
/home/xxx/PKGBUILDS/python-pyrodigal/PKGBUILD: line 28: cd: /home/xxx/PKGBUILDS/python-pyrodigal/src/pyrodigal-2.1.0/build/lib.linux-x86_64-cpython-3.10: No such file or directory
==> ERROR: A failure occurred in check()
```

i have not modified PKGBUILD in any way.

EDIT: from perusing the source directory there is no `lib.linux-x86_64-cpython-3.10` folder but a folder named `lib.linux-x86_64-cpython-310` does exist. so it looks like exported `pyver` variables needs modifications as below

```shell
local pyver=$(python -c 'import sys; print("{}{}".format(*sys.version_info[:2]))')
```

**Comment by althonos** [comment]
Hi @kbipinkumar, thanks for the bug report, this should be fixed now.
