### ISSUE TITLE
Bioconda build on OSx after recent changes

### ISSUE THREAD

**Issue by raufs** [althonos/pyrodigal#37]
Hi Martin,

Bioconda recently had a major update which caused some recipes to fail to build, including pyrodigal, but only on OSx: https://github.com/bioconda/bioconda-recipes/wiki/build-failures 

Just want to report it here in case you had not seen it.

Thank you again for all the awesome Python bindings and software!
Rauf

**Comment by althonos** [comment]
Thanks for the heads-up!

It looks like there is an issue with the `cpu-features` compilation, which is okay, given that I was planning to replace it by the [`archspec`](https://github.com/archspec/archspec) package for convenience. I'll make the necessary changes and hopefully the new version builds without issue.

**Comment by raufs** [comment]
Thank you Martin for updating pyrodigal to the next version so quickly! I saw you ran into the same issue I have been seeing in bioconda for zol with build failure on OSx still occurring. I was secretly hoping by resolving pyrodigal's built it might resolve the issue for zol as well, which uses it as a key dependency. 

I think pyrodigal is super lightweight, but do you think by chance there is a dependency upstream that might have recently broken for it during the recent bioconda changes, some of the tools with broken recipes have lots of dependent packages such as blast it seems. 

https://github.com/bioconda/bioconda-recipes/wiki/build-failures

**Comment by raufs** [comment]
Hi Martin, looks like I was able to get the checks to pass and build on OSx after changing `python` listing in the requirements - run subsection to `python >=3`. Not sure why this solved the issue exactly and because artifacts are not building/fetching currently, but will update this comment if the real world tests turn out problematic -  I think it just means that python3 is required to be present on the target system.

**Comment by althonos** [comment]
Hi @raufs , Thanks for the hint :) I tried updating the `run` section as well but I'm still hitting issues in the build process. I'll try to force `python >=3` in all stages of the recipe to see if it resolves something.

**Comment by raufs** [comment]
Something odd is going on with bioconda utils I think, now getting the same error except on linux checks and the last successful commit for zol, after adding the `>3`, didn't actually get registered.  

:man_shrugging: hopefully gets resolved

**Comment by althonos** [comment]
Yes this is annoying, and since it impacts a lot of people I guess the Bioconda people will have to resolve it at some point but we can only wait for now :unamused: If this takes too long I'll create a recipe on `conda-forge`.

**Comment by althonos** [comment]
Looks like it's fixed :)
