### ISSUE TITLE
A way to obtain the nucleotide sequence of a gene

### ISSUE THREAD

**Issue by EnzoAndree** [althonos/pyrodigal#4]
Hello!, Congratulations for this implementation.

Although I have a question. is it possible to get the nucleotide sequence of a gene from the pyrodigal prediction? something like the "translate" method, but with the nucleotide sequence.

I need that in downstream analysis to do codon alignment.  

Best regards.
Enzo

**Comment by althonos** [comment]
Hi @EnzoAndree , thanks for the kind message! 

At the moment it's not possible (you'd need to slice the original sequence yourself) but i'm changing how the sequences are handled internally and I can add that in a next version. Cheers!

**Comment by althonos** [comment]
Hi again, `v0.5.4` is out. With it you can get the sequence of a prediction as a string:
```
p = pyrodigal.Pyrodigal(meta=True)
for prediction in p.find_genes(seq):
    gene_sequence = prediction.sequence()
```

Note that any unknown character (none of A/T/G/C) will be converted as a N, so the sequence you get from that method may not be 100% the same as if you manually indexed the source sequence with the start and end coordinates.

Cheers!
