### ISSUE TITLE
Conda availability of 2.2.0 and 2.3.0 restricted to Python 3.11

### ISSUE THREAD

**Issue by oschwengers** [althonos/pyrodigal#41]
Hi Martin,
thanks so much for this wonderful Prodigal replacement - we use it a lot!

Due to https://anaconda.org/bioconda/pyrodigal/files, Pyrodigal `v2.2.0` and `v2.3.0` are only available for Python `3.11`.

Since we've included Pyrodigal in Bakta and other 3rd party-deps are not (yet) available for Python `3.11`, this is a bit of a show-stopper. It would be very useful if the newer versions were also available for Python `3.8` - `3.10`. Would that be possible?

Thanks again and best regards!

**Comment by althonos** [comment]
Hi @oschwengers !

This is strange because I just pushed an update for PyHMMER which was also updated to use Cython 3.0 now, and there I have Bioconda packages for Python `3.8` to `3.11`. Any idea why packages are not being built for Python `3.8` - `3.10`?

**Comment by oschwengers** [comment]
No, unfortunately, I have no clue why this is the case. But, due to https://anaconda.org/bioconda/pyhmmer/files, there is no PyHMMER for Python `3.11`. Maybe somehow related?

**Comment by althonos** [comment]
This is puzzling, I really don't know how Bioconda chooses the platform to build.

**Comment by mencian** [comment]
Greetings! I have edit the pyrodigal recipe to build on Python versions 3.8-3.10 and opened a [PR](https://github.com/bioconda/bioconda-recipes/pull/42619) over at bioconda-recipes.

**Comment by althonos** [comment]
Ah thank you @mencian !
