### ISSUE TITLE
gzip support

### ISSUE THREAD

**Issue by jianshu93** [althonos/pyrodigal#47]
Hello Team,

Any possibilities to provide gzip support for input fasta files? This is very useful for very large contig files from metagenomes.  We can use zcat et.al., to unzip and stream the input but still not so convenient. 

Thanks,

Jianshu

**Comment by althonos** [comment]
This is already supported since `v2.2.0`, `gzip` or `bzip2` compression of input files is automatically detected and handled to load data.
