### ISSUE TITLE
command line replacement for prodigal

### ISSUE THREAD

**Issue by alexcritschristoph** [althonos/pyrodigal#56]
I really appreciate pyrodigal.

Something that I think could be helpful for the community would be a command line interface for it that is essentially a drop in replacement for prodigal, with multi-threading enabled, so someone could run:

```
pyrodigal -i big_metagenome.fasta -a amino_acids.faa -d genes.fna -t 12
```

You might not need all of the parameters of prodigal, just `-meta`, `-d`, `-a`. Curious if you would have the time for it.

**Comment by althonos** [comment]
There is one already, except the `-t` option is named `-j` / `--jobs` 😅

**Comment by alexcritschristoph** [comment]
OMG I'm a idiot

This is awesome, thank you!

**Comment by althonos** [comment]
I've added an explicit section to the documentation now: https://pyrodigal.readthedocs.io/en/stable/guide/cli.html
