### ISSUE TITLE
alternative genetic code

### ISSUE THREAD

**Issue by anagtz** [althonos/pyrodigal#59]
Hi,

Is there a way to provide an alternative translation table, other than the ones specified by numbers (eg... 11, 25, 4...)???

Thanks in advance,
Ana

**Comment by althonos** [comment]
Hi,
At the moment it's not possible because Prodigal needs to use numbered translation tables internally to figure out the STOP codons before gene calling, adding support for custom ones would require a bit more refactoring for which I don't have time to invest right now.

**Comment by anagtz** [comment]
I understand. Thank you so much for your answer.
