### ISSUE TITLE
Proteins with more than 100K amino acids

### ISSUE THREAD

**Issue by ericolo** [althonos/pyrodigal#60]
Hello !

This is not really an issue but it can be for downstream analyses, so maybe worth mentioning:

I'm predicting the proteins for a bunch of MAGs and in a couple cases my downstream annotations were stopped because of proteins having more than 100K amino acids. Those are certainly not real and are due to a large number of unknown bases in the genome, so the composition of such proteins is mostly Xs.

Here are some NCBI genomes for which this happens: 
GCA_900004565.1
GCF_014216935.1
GCF_001865985.1
GCA_900004565.1
GCF_902166545.1
GCF_014217055.1
GCA_001261935.1
GCA_900004565.1

I'm using pyrodigal like this:
`pyrodigal -i genome.fna -a genome.faa -d genome.out`

Maybe these could be discarded during the prediction ? 
Or maybe there's already a warning somewhere ? 

Thanks !
Eric

**Comment by althonos** [comment]
This happens because there is a start and a stop codon on each sides of a NNNNN region. You can prevent genes from being called across these regions using the `-m` flag, just like in the original Prodigal which has the same behaviour.

**Comment by ericolo** [comment]
Oh got it thanks, sorry for not thoroughly reading the manual first 

Thanks a lot !
Eric

**Comment by althonos** [comment]
I suppose I can close this too :smile:
