### ISSUE TITLE
Error: list index out of range

### ISSUE THREAD

**Issue by ericolo** [althonos/pyrodigal#61]
Hello ! 

I get this error message with this specific NCBI genome: GCF_019971195.1

`pyrodigal -i all_genomes/GCF_019971195.1.fna -a test.faa -o test.out`
`Error: list index out of range`

That genome looks fine, and with the original prodigal this same command works.
I have no idea where the issue could come from.

Thanks in advance, 
Eric

**Comment by althonos** [comment]
Hi Eric, I downloaded the genome from the NCBI server: (https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/019/971/195/GCF_019971195.1_ASM1997119v1/GCF_019971195.1_ASM1997119v1_genomic.fna.gz) and i could run your command without problem on my machine, so I'm not sure what is going on. What version of `pyrodigal` are you running, and on what platform?

**Comment by ericolo** [comment]
I have v3.4.1, installed a couple months ago through mamba, I updated it to the latest and it gave me the same error, then I compared your genome file to mine and I realized mine was missing contigs, and an empty header was the reason of the error:

`>NZ_CAUJRJ010000071.1 Neisseria subflava strain CCUG 24960 306219, whole genome shotgun sequence`
`CGCAGTTTGAACGGCGATACGCCGTTTGAGGTCTTGCAGGCTTCATTCTCAACCTGTGGTGTAAACAACGCAACGTTTTC
CTACACATAATCCAAATACCAAGAATGCACGAACACTCAATAGGTATCGATTCATCAATATTCTTGCACCCTTACCCCAT
CACCTATCGCCAAACCGATAGAACCGACAGGTATGTAAAAAGCCCCCG`
`>`  

Sorry once again for the trivial error and the false alarm, I hope I didn't propagate this to my entire dataset

Thanks a lot !
Eric

**Comment by althonos** [comment]
Glad to hear that! Indeed with an empty FASTA header line, I'm getting the issue now. Still, I don't think the parser should fail on an empty FASTA header, or if it does it should at least be informative about it. I'll make a patch to raise a warning instead :+1:

**Comment by althonos** [comment]
Fixed in `v3.5.2`.
