### ISSUE TITLE
Understanding RBS motif output

### ISSUE THREAD

**Issue by Ge0rges** [althonos/pyrodigal#62]
Hello,

My goal is to precisely identify the RBS motif of my gene sequence. To do so I use the spacer length to determine a window in which to look for the motif (e.g. I take the upper bounder spacer and add 10bp). 

My issue is in understanding the possible RBS motifs. For example:
- I understand that `GGAG/GAGG` means I should look for both `GGAG` and `GAGG`.
- I'm unsure how to handle `GGxGG` for example. The original prodigal paper says `x` indicates allowed mismatch. So should I teat that as `GGNGG` where N is any of `A,G,T,C` as in the IUPAC code? Or is `x` indicating a mismatch one one the adjacent base pairs (e.g. `GAGG` would be valid as well as `GGTG`).
- Finally, I'm unsure how to handle `4Base/6BMM` and `3Base/5BMM`.

Thank for any tips

**Comment by althonos** [comment]
Hi @Ge0rges,

You can find more information in the supplementary table here: https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-11-119/tables/2

`GGxGG` means any of `GGAGG`, `GGTGG`, etc. The `3Base/5BMM` corresponds to bin number 2, so one of `GGA`, `GAG`, `AGG`, or a 5 base motif with a mismatch, one of `AGxAG` or `GGxGG`. The `4Base/6BMM` corresponds to bin number 3, so one of `AGGA`, `GGAG`, `GAGG`, or a 6 base motif with a mismatch, `AGxAGG`, `AGGxGG`.
