### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by yurivict** [althonos/pyrodigal#63]
In previous versions (3.5.2) tests were run with ```python -m unittest discover -vv```.
This doesn't work in 3.6.3

The [Installation page](https://pyrodigal.readthedocs.io/en/stable/guide/install.html) in the documentation doesn't explain this.

How to run tests?

**Comment by althonos** [comment]
Hi! This should have been in `CONTRIBUTING.md` / [contribution guide](https://pyrodigal.readthedocs.io/en/stable/guide/contributing.html) but I forgot to update it. 

You need to `pip install` the package first, and then run `python -m unittest pyrodigal.tests -vv`.
